# Generated by Django 5.1.3 on 2024-11-25 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0002_alter_faculty_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='email',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='faculty',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
