# Generated by Django 5.1.3 on 2024-11-25 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0003_faculty_email_alter_faculty_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
